services:
    nginx:
        image: nginx:1.25
        ports:
            - "80:80"
        volumes:
            - "./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf"
            - ".:/app:cached"
        depends_on:
            - php
    php:
        build:
            context: ./docker-configs/php
        volumes:
            - "./docker-configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./docker-configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
            - ".:/app:cached"
        ports:
            - 9003:9003
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
